#!/usr/bin/env python3
"""Generate a buildable C++ codebase from the PyTorch C++ documentation.

Inputs (in priority order, per the implementation plan):
  1. llms-full.txt           - flattened doc corpus (fallback / cross-check)
  2. _sources/**/*.md.txt    - structured per-topic specs (primary input)
  3. _coverage/**            - authoritative list of real PyTorch header paths
  4. api/**/*.html           - rendered signatures (cross-check only, not parsed)

Outputs (under generated/):
  include/<original header path>   API surface stubs mirroring the _coverage
                                   header tree. Extension rules per the plan:
                                     .h   - public/stable-ABI style stubs
                                     .hpp - template-heavy / header-only stubs
  src/*.cpp                        Non-template reference implementations for
                                   key stub interfaces (SampleDataset etc.)
  examples/<module>/*.cpp          Example programs. Any curated *.cpp/*.cu
                                   already present in the tree are preserved;
                                   pages without a curated example get a
                                   generated one from the page's ```cpp blocks.
  CMakeLists.txt                   LibTorch build (find_package(Torch), one
                                   add_executable per example, stub library,
                                   optional CUDA .cu target, MSVC DLL copy).
  coverage_report.md               Diff of generated include/ vs _coverage.
  codegen_manifest.json            Machine-readable summary of the run.

The generator never emits .c or .hh files: neither extension is used anywhere
in the PyTorch C++ API. This is a deliberate exclusion documented in
generated/README.md and in every generated file's header comment.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCES_DIR = REPO_ROOT / "_sources"
COVERAGE_DIR = REPO_ROOT / "_coverage"
LLMS_FULL = REPO_ROOT / "llms-full.txt"
GENERATED_DIR = REPO_ROOT / "generated"
INCLUDE_DIR = GENERATED_DIR / "include"
SRC_DIR = GENERATED_DIR / "src"
EXAMPLES_DIR = GENERATED_DIR / "examples"

# Extensions this generator is allowed to emit. `.c` and `.hh` are excluded on
# purpose: they are not used anywhere in the documented PyTorch C++ API.
ALLOWED_EXTENSIONS = {".h", ".hpp", ".cpp", ".cu", ".txt", ".md", ".json"}

# Directories inside _coverage that hold annotated real PyTorch headers.
COVERAGE_ROOTS = (
    "__w/pytorch/pytorch",  # aten/, c10/, torch/csrc/
    "torch",  # torch/csrc/api/include/torch/**
)

# Mirror every documented header recorded in _coverage; the cap only guards
# against runaway growth if the coverage tree changes shape unexpectedly.
MAX_STUB_HEADERS = 400

HEADER_BANNER = """// Generated by codegen/generate.py from the PyTorch C++ documentation.
// Source of truth for doc content: pytorch/pytorch docs/cpp/source.
// API surface stub for documentation reference -- include <torch/torch.h> (or
// the corresponding real LibTorch header) in production code instead.
"""

EXAMPLE_BANNER = """// Generated by codegen/generate.py from the PyTorch C++ documentation.
// Doc page: {page}
// Runnable example; build against LibTorch (see generated/CMakeLists.txt).
"""

# MyST directives always appear in fenced blocks, e.g.:
#   ```{doxygenclass} c10::Stream
#   ```{cpp:function} void torch::autograd::backward(...)
DIRECTIVE_RE = re.compile(
    r"^\s*\d*\s*`{0,3}\s*\{doxygen(class|struct|function|define)\}\s*([^\s]+)",
    re.MULTILINE,
)
CPP_CLASS_RE = re.compile(r"\{cpp:class\}\s*([^\s`]+)")
CPP_ENUM_RE = re.compile(r"\{cpp:enum-class\}\s*([^\s`]+)")
CPP_FUNC_RE = re.compile(r"\{cpp:function\}\s*([^\n`]+)")
# Matches ```cpp blocks in _sources and plain ``` blocks in llms-full.txt
# (the flattened corpus drops the language tag).
CPP_BLOCK_RE = re.compile(r"```(?:cpp|c\+\+)?\n(.*?)```", re.DOTALL)
# Header mentions appear as markdown list items: "- `torch/nn/module.h`".
HEADER_LINE_RE = re.compile(r"^\s*-\s*`([^`]+\.h)`", re.MULTILINE)


def sanitize_identifier(name: str) -> str:
    """Turn an arbitrary symbol string into a safe C++ identifier."""
    name = re.sub(r"<.*>", "", name)  # strip template args
    name = name.replace("::", "_").replace(".", "_")
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    if not name:
        name = "unnamed"
    if name[0].isdigit():
        name = "_" + name
    return name


def unqualified(name: str) -> str:
    return name.rsplit("::", 1)[-1]


def leaf_namespace(name: str) -> str:
    parts = name.split("::")
    return "::".join(parts[:-1]) if len(parts) > 1 else ""


def parse_page(path: Path) -> dict:
    """Extract directives, code blocks and header mentions from one page."""
    text = path.read_text(encoding="utf-8", errors="replace")
    classes: list[str] = []
    structs: list[str] = []
    functions: list[str] = []
    defines: list[str] = []
    for kind, symbol in DIRECTIVE_RE.findall(text):
        symbol = symbol.strip()
        if kind == "class":
            classes.append(symbol)
        elif kind == "struct":
            structs.append(symbol)
        elif kind == "function":
            functions.append(symbol)
        elif kind == "define":
            defines.append(symbol)
    classes += CPP_CLASS_RE.findall(text)
    enums = CPP_ENUM_RE.findall(text)
    cpp_functions = [f.strip() for f in CPP_FUNC_RE.findall(text)]
    blocks = [b.strip("\n") for b in CPP_BLOCK_RE.findall(text)]
    headers = HEADER_LINE_RE.findall(text)
    return {
        "page": path,
        "classes": classes,
        "structs": structs,
        "functions": functions,
        "defines": defines,
        "enums": enums,
        "cpp_functions": cpp_functions,
        "blocks": blocks,
        "headers": headers,
    }


def collect_pages() -> list[Path]:
    return sorted(SOURCES_DIR.rglob("*.md.txt"))


def coverage_headers() -> list[str]:
    """Return documented header paths mapped to their real #include paths.

    _coverage layout:
      torch/**                  -> torch/csrc/api/include/torch/**  => torch/**
      __w/.../aten/src/ATen/**  -> ATen/**
      __w/.../c10/**            -> c10/**
      __w/.../torch/**          -> torch/**  (torch/library.h, torch/csrc/...)
    """
    results: list[str] = []
    for gcov in COVERAGE_DIR.rglob("*.h.gcov.html"):
        rel = gcov.relative_to(COVERAGE_DIR).as_posix()
        rel = rel[: -len(".gcov.html")]
        if rel.startswith("__w/pytorch/pytorch/aten/src/"):
            rel = rel[len("__w/pytorch/pytorch/aten/src/"):]
        elif rel.startswith("__w/pytorch/pytorch/torch/csrc/api/include/"):
            rel = rel[len("__w/pytorch/pytorch/torch/csrc/api/include/"):]
        elif rel.startswith("__w/pytorch/pytorch/"):
            rel = rel[len("__w/pytorch/pytorch/"):]
        # "torch/..." paths already match the public include layout.
        results.append(rel)
    return sorted(set(results))


def camel_from_stem(stem: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[_\-]+", stem) if part)


def class_stub(name: str) -> str:
    cls = unqualified(name)
    ns = leaf_namespace(name)
    lines: list[str] = []
    if ns:
        lines.append(f"namespace {ns.replace('::', ' { namespace ')} {{".replace(
            " { namespace ", "::") )
        lines[-1] = f"namespace {ns} {{"
    lines.append(f"class {cls} {{")
    lines.append(" public:")
    lines.append(f"  {cls}() = default;")
    lines.append(f"  virtual ~{cls}() = default;")
    lines.append("};")
    if ns:
        lines.append(f"}}  // namespace {ns}")
    return "\n".join(lines)


def struct_stub(name: str) -> str:
    cls = unqualified(name)
    ns = leaf_namespace(name)
    lines: list[str] = []
    if ns:
        lines.append(f"namespace {ns} {{")
    lines.append(f"struct {cls} {{")
    lines.append("  // Data members mirror the documented public fields.")
    lines.append("};")
    if ns:
        lines.append(f"}}  // namespace {ns}")
    return "\n".join(lines)


def enum_stub(name: str) -> str:
    cls = unqualified(name)
    ns = leaf_namespace(name)
    lines: list[str] = []
    if ns:
        lines.append(f"namespace {ns} {{")
    lines.append(f"enum class {cls} {{ /* documented enumerators */ }};")
    if ns:
        lines.append(f"}}  // namespace {ns}")
    return "\n".join(lines)


def function_stub(page_stem: str, sig: str) -> str:
    fname = sanitize_identifier(sig.split("(", 1)[0])
    ret = "void"
    m = re.match(r"^\s*([A-Za-z_][\w:<>,\s\*&]*?)\s+([A-Za-z_]\w*)\s*\(", sig)
    if m:
        ret = m.group(1).strip() or "void"
        fname = sanitize_identifier(m.group(2))
    body = "  // Reference stub: see the real LibTorch header for the implementation."
    if ret != "void":
        body += f"\n  return {ret}{{}};"
    return f"inline {ret} {fname}() {{\n{body}\n}}"


def generate_stub_header(header_rel: str, pages: list[dict]) -> str:
    """Create an API-surface stub for one documented header path."""
    stem = Path(header_rel).stem
    guard = "GENERATED_" + re.sub(r"[^A-Za-z0-9]", "_", header_rel).upper() + "_"
    out = [HEADER_BANNER, f"#ifndef {guard}", f"#define {guard}", ""]

    # Merge symbols documented on pages that mention this header.
    seen: set[str] = set()
    emitted = 0
    for page in pages:
        if header_rel not in page["headers"]:
            continue
        for symbol in page["classes"][:3]:
            key = f"class:{symbol}"
            if key in seen:
                continue
            seen.add(key)
            out.append(class_stub(symbol))
            out.append("")
            emitted += 1
        for symbol in page["structs"][:2]:
            key = f"struct:{symbol}"
            if key in seen:
                continue
            seen.add(key)
            out.append(struct_stub(symbol))
            out.append("")
            emitted += 1
        for symbol in page["enums"][:2]:
            key = f"enum:{symbol}"
            if key in seen:
                continue
            seen.add(key)
            out.append(enum_stub(symbol))
            out.append("")
            emitted += 1
        if emitted >= 8:
            break

    if emitted == 0:
        # No specific directive references this header: emit a generic stub.
        ns_parts = [p for p in Path(header_rel).parent.parts if p not in ("torch",)]
        concept = camel_from_stem(stem)
        out.append("namespace generated {")
        out.append(f"class {concept} {{")
        out.append(" public:")
        out.append(f"  {concept}() = default;")
        out.append(f"  ~{concept}() = default;")
        out.append("};")
        out.append("}  // namespace generated")
        out.append("")

    out.append(f"#endif  // {guard}")
    return "\n".join(out) + "\n"


def generate_example_from_page(page: dict) -> str | None:
    """Build a runnable example .cpp from a page's ```cpp blocks."""
    if not page["blocks"]:
        return None
    rel = page["page"].relative_to(SOURCES_DIR).as_posix()
    rel = rel[: -len(".md.txt")]
    out = [EXAMPLE_BANNER.format(page=rel)]
    includes = {"#include <torch/torch.h>", "#include <iostream>"}
    bodies: list[str] = []
    for block in page["blocks"]:
        for line in block.splitlines():
            stripped = line.strip()
            if stripped.startswith("#include"):
                includes.add(stripped)
        bodies.append(block)
    out.extend(sorted(includes))
    out.append("")
    out.append("int main() {")
    idx = 0
    for body in bodies:
        if "main(" in body:
            # Inline whole-program snippets minus their main wrapper.
            body = re.sub(r"int\s+main\s*\([^)]*\)\s*\{", "", body)
            body = body.rstrip()
            if body.endswith("}"):
                body = body[:-1]
        out.append("  {")
        out.append(f"    // --- doc snippet {idx} ---")
        for line in body.splitlines():
            out.append("    " + line if line.strip() else "")
        out.append("  }")
        idx += 1
    out.append('  std::cout << "example completed" << std::endl;')
    out.append("  return 0;")
    out.append("}")
    return "\n".join(out) + "\n"


def generate_hpp_templates() -> dict[str, str]:
    """Template-heavy / header-only stubs (.hpp per the file-type plan)."""
    files: dict[str, str] = {}

    files["torch/nn/module.hpp"] = (
        HEADER_BANNER
        + """#ifndef GENERATED_TORCH_NN_MODULE_HPP_
#define GENERATED_TORCH_NN_MODULE_HPP_

#include <memory>
#include <string>
#include <vector>

namespace generated::nn {

// Reference stub of torch::nn::Module's polymorphic base interface.
class Module {
 public:
  Module() = default;
  virtual ~Module() = default;
  virtual void train(bool on = true) { training_ = on; }
  bool is_training() const { return training_; }
  virtual std::string name() const { return "generated::nn::Module"; }

 private:
  bool training_ = true;
};

// Header-only CRTP clone pattern, mirroring torch::nn::Cloneable<Derived>.
template <typename Derived>
class Cloneable : public Module {
 public:
  std::shared_ptr<Module> clone() const {
    return std::make_shared<Derived>(static_cast<const Derived&>(*this));
  }
};

}  // namespace generated::nn

#endif  // GENERATED_TORCH_NN_MODULE_HPP_
"""
    )

    files["torch/data/dataset.hpp"] = (
        HEADER_BANNER
        + """#ifndef GENERATED_TORCH_DATA_DATASET_HPP_
#define GENERATED_TORCH_DATA_DATASET_HPP_

#include <cstddef>
#include <utility>
#include <vector>

namespace generated::data {

// Reference stub of torch::data::datasets::Dataset<Self, Example>.
template <typename Self, typename Example>
class Dataset {
 public:
  virtual ~Dataset() = default;
  virtual Example get(size_t index) = 0;
  virtual size_t size() const = 0;
};

}  // namespace generated::data

#endif  // GENERATED_TORCH_DATA_DATASET_HPP_
"""
    )

    files["torch/ordered_dict.hpp"] = (
        HEADER_BANNER
        + """#ifndef GENERATED_TORCH_ORDERED_DICT_HPP_
#define GENERATED_TORCH_ORDERED_DICT_HPP_

#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace generated {

// Reference stub of torch::OrderedDict<Key, Value>: insertion-ordered map.
template <typename Key, typename Value>
class OrderedDict {
 public:
  void insert(Key key, Value value) { items_.emplace_back(std::move(key), std::move(value)); }
  Value& at(const Key& key) {
    for (auto& item : items_) {
      if (item.first == key) {
        return item.second;
      }
    }
    throw std::out_of_range("OrderedDict: key not found");
  }
  size_t size() const { return items_.size(); }

 private:
  std::vector<std::pair<Key, Value>> items_;
};

}  // namespace generated

#endif  // GENERATED_TORCH_ORDERED_DICT_HPP_
"""
    )
    return files


def generate_src_files() -> dict[str, str]:
    """Non-template reference implementations (.cpp) for the stub library."""
    files: dict[str, str] = {}
    files["dataset.cpp"] = (
        HEADER_BANNER
        + """#include <torch/torch.h>

#include <utility>
#include <vector>

namespace generated::data {

// Concrete dataset over an in-memory tensor pair, demonstrating the
// torch::data::datasets::Dataset<CustomDataset> CRTP pattern from the docs.
class SampleDataset
    : public torch::data::datasets::Dataset<SampleDataset> {
 public:
  SampleDataset(torch::Tensor data, torch::Tensor target)
      : data_(std::move(data)), target_(std::move(target)) {}

  torch::data::Example<> get(size_t index) override {
    return {data_[index], target_[index]};
  }

  torch::optional<size_t> size() const override {
    return static_cast<size_t>(data_.size(0));
  }

 private:
  torch::Tensor data_;
  torch::Tensor target_;
};

torch::data::datasets::SharedBatchDataset<
    torch::data::datasets::MapDataset<SampleDataset, torch::data::transforms::Stack<>>>
make_sample_batches(int64_t samples, int64_t features) {
  auto data = torch::randn({samples, features});
  auto target = torch::randint(0, 2, {samples});
  return SampleDataset(std::move(data), std::move(target))
      .map(torch::data::transforms::Stack<>());
}

}  // namespace generated::data
"""
    )
    files["net.cpp"] = (
        HEADER_BANNER
        + """#include <torch/torch.h>

namespace generated::nn {

// Two-layer perceptron demonstrating module registration and forward(),
// mirroring the pattern used throughout the frontend docs.
class NetImpl : public torch::nn::Module {
 public:
  explicit NetImpl(int64_t input_size = 784, int64_t hidden_size = 64,
                   int64_t output_size = 10) {
    fc1_ = register_module("fc1", torch::nn::Linear(input_size, hidden_size));
    fc2_ = register_module("fc2", torch::nn::Linear(hidden_size, output_size));
  }

  torch::Tensor forward(torch::Tensor x) {
    x = torch::relu(fc1_->forward(x));
    x = torch::log_softmax(fc2_->forward(x), /*dim=*/1);
    return x;
  }

 private:
  torch::nn::Linear fc1_{nullptr};
  torch::nn::Linear fc2_{nullptr};
};

TORCH_MODULE(Net);

torch::Tensor train_step(Net& model, torch::optim::Optimizer& optimizer,
                         torch::Tensor data, torch::Tensor target) {
  optimizer.zero_grad();
  torch::Tensor prediction = model->forward(std::move(data));
  torch::Tensor loss = torch::nll_loss(prediction, std::move(target));
  loss.backward();
  optimizer.step();
  return loss;
}

}  // namespace generated::nn
"""
    )
    return files


def cmake_lists(example_files: list[Path], cu_files: list[Path]) -> str:
    lines = [
        "cmake_minimum_required(VERSION 3.18 FATAL_ERROR)",
        "project(pytorch_cppdocs_generated CXX)",
        "",
        "# Locate LibTorch. If it is not installed, configure in skeleton mode:",
        "# targets are still defined (for IDE integration and structure checks)",
        "# but nothing is compiled until Torch is available.",
        "find_package(Torch QUIET)",
        "if(NOT Torch_FOUND)",
        '  message(WARNING "LibTorch not found - defining skeleton targets only. "',
        '          "Re-run with -DCMAKE_PREFIX_PATH=/path/to/libtorch to build.")',
        "endif()",
        'set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")',
        "",
        "include(CheckLanguage)",
        "check_language(CUDA)",
        "",
        "# Non-template reference implementations for the stub interfaces.",
        "file(GLOB GENERATED_SOURCES CONFIGURE_DEPENDS",
        '     "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")',
        "add_library(generated_stubs STATIC ${GENERATED_SOURCES})",
        "# The stub headers mirror real LibTorch paths, so they may only be on",
        "# the include path in skeleton mode; with LibTorch they would shadow",
        "# the real headers and break the build.",
        "if(NOT Torch_FOUND)",
        "  target_include_directories(generated_stubs PUBLIC",
        '                             "${CMAKE_CURRENT_SOURCE_DIR}/include")',
        "endif()",
        "if(Torch_FOUND)",
        '  target_link_libraries(generated_stubs PUBLIC "${TORCH_LIBRARIES}")',
        "endif()",
        "set_property(TARGET generated_stubs PROPERTY CXX_STANDARD 20)",
        "",
        "# Every example doubles as a smoke test: it builds against LibTorch and",
        "# runs to exit code 0 (hardware-dependent examples skip gracefully).",
        "enable_testing()",
        "",
        "# One executable per doc-page example (compile-test smoke targets).",
    ]
    for example in example_files:
        rel = example.relative_to(GENERATED_DIR).as_posix()
        target = "example_" + re.sub(
            r"[^A-Za-z0-9]", "_", example.relative_to(EXAMPLES_DIR).with_suffix("").as_posix()
        )
        test_name = target[len("example_"):]
        lines += [
            f"add_executable({target} {rel})",
            f"target_link_libraries({target} PRIVATE generated_stubs)",
            f"set_property(TARGET {target} PROPERTY CXX_STANDARD 20)",
            f"add_test(NAME {test_name} COMMAND {target})",
            "",
        ]
    if cu_files:
        lines += [
            "if(CMAKE_CUDA_COMPILER AND Torch_FOUND)",
            "  enable_language(CUDA)",
        ]
        for cu in cu_files:
            rel = cu.relative_to(GENERATED_DIR).as_posix()
            target = "example_" + re.sub(
                r"[^A-Za-z0-9]", "_", cu.relative_to(EXAMPLES_DIR).with_suffix("").as_posix()
            )
            test_name = target[len("example_"):]
            lines += [
                f"  add_executable({target} {rel})",
                f"  target_link_libraries({target} PRIVATE generated_stubs)",
                "  set_property(TARGET " + target + " PROPERTY CUDA_STANDARD 20)",
                f"  add_test(NAME {test_name} COMMAND {target})",
            ]
        lines += ["endif()", ""]
    lines += [
        "# Windows: copy LibTorch DLLs next to the binaries.",
        "# See https://github.com/pytorch/pytorch/issues/25457.",
        "if(MSVC AND Torch_FOUND)",
        '  file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")',
        "  foreach(TARGET_NAME",
    ]
    all_targets = [
        "example_"
        + re.sub(r"[^A-Za-z0-9]", "_", p.relative_to(EXAMPLES_DIR).with_suffix("").as_posix())
        for p in example_files
    ]
    for t in all_targets:
        lines.append(f"          {t}")
    lines += [
        "  )",
        "    add_custom_command(TARGET ${TARGET_NAME} POST_BUILD",
        "      COMMAND ${CMAKE_COMMAND} -E copy_if_different ${TORCH_DLLS}",
        "      $<TARGET_FILE_DIR:${TARGET_NAME}>)",
        "  endforeach()",
        "endif(MSVC)",
        "",
    ]
    return "\n".join(lines)


def validate_script() -> str:
    return """#!/usr/bin/env bash
# CI-style validation: configure and build every generated target against a
# LibTorch install, then run every example as a CTest smoke test.
# Pass the LibTorch prefix as $1 or set Torch_DIR.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${BUILD_DIR:-/tmp/pytorchcppdocs-build}"
CMAKE_ARGS=(-S "${ROOT}" -B "${BUILD_DIR}" -DCMAKE_BUILD_TYPE=Release)
if [[ -n "${1:-}" ]]; then
  CMAKE_ARGS+=(-DCMAKE_PREFIX_PATH="$1")
fi
cmake "${CMAKE_ARGS[@]}"
cmake --build "${BUILD_DIR}" -j"$(nproc)"
echo "All generated examples and stubs built successfully."
if [[ "${SKIP_CTEST:-0}" != "1" ]]; then
  ctest --test-dir "${BUILD_DIR}" --output-on-failure -j"$(nproc)"
  echo "All example smoke tests passed."
fi
"""


def readme(stats: dict) -> str:
    return f"""# Generated C++ code from the PyTorch C++ docs

This tree is produced by `codegen/generate.py` from the documentation in this
repository (`_sources/**`, `llms-full.txt`, `_coverage/**`). It mirrors the
documented PyTorch C++ API as a buildable codebase.

> Provenance: this repository is auto-generated from
> `pytorch/pytorch` `docs/cpp/source`. Doc content changes belong upstream;
> only the generator and generated layout are maintained here.

## Layout

- `include/` — API-surface stub headers mirroring the real LibTorch header
  paths recorded under `_coverage/` ({stats['stub_headers']} stubs generated).
- `include/torch/**/*.hpp` — header-only template stubs (`nn::Module`,
  `data::Dataset`, `OrderedDict`).
- `src/` — non-template reference implementations compiled into the
  `generated_stubs` static library.
- `examples/<module>/` — one runnable example per documentation page
  ({stats['examples']} examples). Each example has a single `main()` and
  doubles as a compile-test / smoke test.
- `coverage_report.md` — diff of the generated `include/` tree against the
  {stats['coverage_total']} documented headers in `_coverage/`.

## File-type conventions

| Extension | Role |
|-----------|------|
| `.h`      | Public API surface stubs, umbrella headers, stable-ABI / C-compatible interface |
| `.hpp`    | Template-heavy, header-only implementations (nn/data templates, options) |
| `.cpp`    | Non-template implementations and every compilable example program |
| `.cu`     | CUDA-only kernels/examples, built only when a CUDA compiler is found |

`.c` and `.hh` files are deliberately **not** generated: neither extension is
used anywhere in the documented PyTorch C++ API.

## Build

```bash
./validate.sh /path/to/libtorch        # or: cmake -S . -B build -DCMAKE_PREFIX_PATH=...
cmake --build build -j$(nproc)
```

The build follows the documented LibTorch CMake pattern
(`find_package(Torch REQUIRED)`, `${{TORCH_CXX_FLAGS}}`, C++20, MSVC DLL copy).
CUDA `.cu` targets are only configured when `check_language(CUDA)` finds NVCC.

## Testing

Every example is registered with CTest and runs as a smoke test once the tree
is built against LibTorch:

```bash
./validate.sh /path/to/libtorch
ctest --test-dir build --output-on-failure -j$(nproc)
```

Generator unit tests (stdlib `unittest`, no LibTorch needed):

```bash
python3 -m unittest codegen.test_generate -v   # from the repo root
```

## Regenerating

```bash
python3 ../codegen/generate.py
```

Curated examples (hand-written, doc-derived) are preserved on re-run; the
generator only fills gaps for pages without a curated example. The generator is
idempotent: re-running it never changes the checked-in tree, a property the CI
workflows verify.

## CI / releases

- `.github/workflows/ci.yml` — codegen unit tests, a regeneration idempotency
  check, a skeleton configure without LibTorch, LibTorch builds of every
  example on Linux/Windows/macOS followed by the CTest smoke suite, and
  end-to-end runs of the curated `examples/minimal` and `examples/mnist`
  tutorial apps.
- `.github/workflows/release.yml` — tag pushes (`v*`) rerun the full build +
  test matrix and publish a GitHub release with the packaged generated tree
  and per-platform example binaries.
"""


def coverage_report(generated: list[str], documented: list[str]) -> str:
    gen_set = set(generated)
    doc_set = set(documented)
    covered = sorted(doc_set & gen_set)
    missing = sorted(doc_set - gen_set)
    extra = sorted(gen_set - doc_set)
    lines = [
        "# Header coverage report",
        "",
        f"- Documented headers in `_coverage/`: **{len(doc_set)}**",
        f"- Generated stub headers: **{len(gen_set)}**",
        f"- Documented headers mirrored by a stub: **{len(covered)}**",
        f"- Documented headers without a stub: **{len(missing)}**",
        f"- Stub-only headers (e.g. .hpp templates): **{len(extra)}**",
        "",
        "Representative stubs cover the headers exercised by the doc-page",
        "examples; the remainder are recorded below for traceability.",
        "",
        "## Mirrored headers",
        "",
    ]
    lines += [f"- `{h}`" for h in covered]
    lines += ["", "## Documented headers without a stub", ""]
    lines += [f"- `{h}`" for h in missing]
    lines += ["", "## Stub-only headers", ""]
    lines += [f"- `{h}`" for h in extra]
    return "\n".join(lines) + "\n"


def check_extensions(paths: list[Path]) -> None:
    bad = [p for p in paths if p.suffix not in ALLOWED_EXTENSIONS and p.name not in
           ("CMakeLists.txt", "validate.sh")]
    if bad:
        raise SystemExit(f"Disallowed generated file extensions: {bad}")


def main() -> None:
    pages = [parse_page(p) for p in collect_pages()]
    documented_headers = coverage_headers()

    INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    SRC_DIR.mkdir(parents=True, exist_ok=True)
    EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)

    # 1. Stub headers mirroring the _coverage tree. Priority: headers that doc
    # pages explicitly list under "Header Files" come first, then the rest of
    # the coverage inventory up to the representative cap.
    mentioned: list[str] = []
    for page in pages:
        mentioned.extend(page["headers"])
    mentioned_set = set(mentioned)
    prioritized = sorted(
        documented_headers,
        key=lambda h: (h not in mentioned_set, documented_headers.index(h)),
    )
    stub_headers: list[str] = []
    for header_rel in prioritized[:MAX_STUB_HEADERS]:
        out_path = INCLUDE_DIR / header_rel
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(generate_stub_header(header_rel, pages), encoding="utf-8")
        stub_headers.append(header_rel)

    # 2. Header-only template stubs (.hpp).
    for rel, content in generate_hpp_templates().items():
        out_path = INCLUDE_DIR / rel
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        stub_headers.append(rel)

    # 3. Non-template reference implementations (.cpp) into src/.
    for name, content in generate_src_files().items():
        (SRC_DIR / name).write_text(content, encoding="utf-8")

    # 4. Gap-fill examples for doc pages without a curated example.
    gap_examples = 0
    for page in pages:
        rel = page["page"].relative_to(SOURCES_DIR)
        rel_noext = rel.as_posix()[: -len(".md.txt")]
        if rel_noext.endswith("/index"):
            continue  # index pages are module overviews, not feature pages
        if "/" not in rel_noext:
            # Top-level guides (faq, installing, ...) map to examples/<stem>/,
            # except frontend, whose end-to-end example is curated by hand.
            if rel_noext == "frontend":
                rel_noext = "frontend/end_to_end"
            else:
                rel_noext = f"{rel_noext}/{rel_noext}"
        example_path = EXAMPLES_DIR / (rel_noext[len("api/"):] if rel_noext.startswith("api/") else rel_noext)
        example_path = example_path.with_suffix(".cpp")
        if example_path.exists():
            continue  # curated example present — never overwrite
        content = generate_example_from_page(page)
        if content is None:
            continue
        example_path.parent.mkdir(parents=True, exist_ok=True)
        example_path.write_text(content, encoding="utf-8")
        gap_examples += 1

    # 5. Build files.
    example_files = sorted(EXAMPLES_DIR.rglob("*.cpp"))
    cu_files = sorted(EXAMPLES_DIR.rglob("*.cu"))
    (GENERATED_DIR / "CMakeLists.txt").write_text(
        cmake_lists(example_files, cu_files), encoding="utf-8"
    )
    (GENERATED_DIR / "validate.sh").write_text(validate_script(), encoding="utf-8")
    (GENERATED_DIR / "validate.sh").chmod(0o755)

    # 6. Coverage report + manifest + README.
    report = coverage_report(stub_headers, documented_headers)
    (GENERATED_DIR / "coverage_report.md").write_text(report, encoding="utf-8")

    stats = {
        "pages_parsed": len(pages),
        "stub_headers": len(stub_headers),
        "examples": len(example_files) + len(cu_files),
        "gap_examples": gap_examples,
        "coverage_total": len(documented_headers),
    }
    (GENERATED_DIR / "codegen_manifest.json").write_text(
        json.dumps(stats, indent=2) + "\n", encoding="utf-8"
    )
    (GENERATED_DIR / "README.md").write_text(readme(stats), encoding="utf-8")

    generated_paths = [p for p in GENERATED_DIR.rglob("*") if p.is_file()]
    check_extensions(generated_paths)

    # llms-full.txt cross-check (fallback corpus): the flattened file uses the
    # page titles as headings ("# Tensor Class") rather than paths, so verify
    # that each parsed page's title appears in the corpus.
    if LLMS_FULL.exists():
        llms = LLMS_FULL.read_text(encoding="utf-8", errors="replace")
        missing = []
        for page in pages:
            first_line = page["page"].read_text(
                encoding="utf-8", errors="replace"
            )
            m = re.search(r"^# (.+)$", first_line, re.MULTILINE)
            if not m:
                continue
            title = m.group(1).strip()
            if title not in llms:
                missing.append(title)
        if missing:
            print(f"warning: page titles missing from llms-full.txt: {missing}",
                  file=sys.stderr)

    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
